#!/bin/bash

# Enable logs
exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

# Install Git
echo "Installing Git"
yum update -y
yum install git -y

# Install Node JS
yes | sudo apt update
yes | sudo apt install nodejs
yes | sudo apt install npm

npm install pm2 -g
