#!/bin/bash

# Enable logs
exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

# Update Packages
yes | sudo apt update
yes | sudo apt install net-tools

# Install Git
yes | sudo apt install git

# Install Node JS and packages
yes | sudo apt install nodejs
yes | sudo apt install npm

# Install dependencies
echo "Installing dependencies"
npm i express
npm i body-parser
npm install pm2 -g

# Clone website code
echo "Cloning website"
mkdir -p /demo-website
cd /demo-website
git clone https://github.com/ocecenas/aws-demos.git .
cd dynamic-website-scaling

# Forward port 80 traffic to port 3000
echo "Forwarding 80 -> 3000"
sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 3000

# Install & use pm2 to run Node app in background
sudo node app.js
